# Spark MLLib


In [1]:
#import pakages 
from pyspark import SparkContext
from pyspark.mllib.stat import Statistics

In [2]:
# Use the existing SparkContext
sc=SparkContext.getOrCreate()

In [3]:
#data rdd of vectors 
dataMatrix = sc.parallelize([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [6]:
# Compute summarystatistics
summary=Statistics.colStats(dataMatrix)
print(summary.mean())
print(summary.variance())
print(summary.numNonzeros())

[5.5 6.5 7.5]
[15. 15. 15.]
[4. 4. 4.]
